from __future__ import annotations

from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from src.common.types import Event, KeywordHit, VectorHit, VectorItem


@dataclass(slots=True, kw_only=True)
class Job:
    job_id: str
    job_type: str
    payload: dict
    retry_count: int = 0
    max_retries: int = 3
    locked_until: float = 0.0


class RelationalStore(Protocol):
    async def init(self) -> None: ...
    async def close(self) -> None: ...
    async def execute(self, sql: str, *params: Any) -> int: ...
    async def fetch_one(self, sql: str, *params: Any) -> dict | None: ...
    async def fetch_all(self, sql: str, *params: Any) -> list[dict]: ...
    def transaction(self) -> Transaction: ...
    async def listen(self, channel: str) -> AsyncIterator[str]: ...
    async def notify(self, channel: str, payload: str = "") -> None: ...


class Transaction(Protocol):
    async def __aenter__(self) -> Transaction: ...
    async def __aexit__(self, *args: Any) -> None: ...
    async def execute(self, sql: str, *params: Any) -> int: ...
    async def fetch_one(self, sql: str, *params: Any) -> dict | None: ...
    async def fetch_all(self, sql: str, *params: Any) -> list[dict]: ...


class VectorIndex(Protocol):
    async def init(self) -> None: ...
    async def upsert(self, namespace: str, items: list[VectorItem]) -> None: ...
    async def search(
        self,
        namespace: str,
        query_vec: list[float],
        top_k: int,
        user_id: str,
        filter: dict | None = None,
    ) -> list[VectorHit]: ...
    async def delete(self, namespace: str, ids: list[str]) -> None: ...


class KeywordIndex(Protocol):
    async def init(self) -> None: ...
    async def index(
        self,
        namespace: str,
        doc_id: str,
        text: str,
        user_id: str,
        metadata: dict | None = None,
    ) -> None: ...
    async def search(
        self,
        namespace: str,
        query: str,
        top_k: int,
        user_id: str,
        filter: dict | None = None,
    ) -> list[KeywordHit]: ...
    async def delete(self, namespace: str, doc_ids: list[str]) -> None: ...


class StorageBackend(Protocol):
    async def init(self) -> None: ...
    async def put(
        self, key: str, data: bytes, mime_type: str = "application/octet-stream"
    ) -> str: ...
    async def put_stream(
        self, key: str, stream: AsyncIterator[bytes], mime_type: str = "application/octet-stream"
    ) -> str: ...
    async def get(self, key: str) -> bytes: ...
    async def get_stream(self, key: str) -> AsyncIterator[bytes]: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
    async def signed_url(self, key: str, expires_in: int = 3600) -> str: ...


class Cache(Protocol):
    async def init(self) -> None: ...
    async def get(self, key: str) -> Any | None: ...
    async def set(self, key: str, value: Any, ttl: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def incr(self, key: str, amount: int = 1, ttl: int | None = None) -> int: ...


class EventBus(Protocol):
    async def init(self) -> None: ...
    async def publish(self, event: Event) -> None: ...
    def subscribe(self, filter: dict | None = None) -> EventSubscription: ...
    async def replay(self, run_id: str, since_seq: int = 0) -> AsyncIterator[Event]: ...
    async def shutdown(self, timeout: float = 30.0) -> None: ...


class EventSubscription(Protocol):
    def __aiter__(self) -> EventSubscription: ...
    async def __anext__(self) -> Event: ...
    async def aclose(self) -> None: ...


class JobQueue(Protocol):
    async def init(self) -> None: ...
    async def enqueue(
        self,
        job_type: str,
        payload: dict,
        *,
        priority: int = 0,
        scheduled_at: float | None = None,
        max_retries: int = 3,
    ) -> str: ...
    async def claim_next(
        self, worker_id: str, job_types: list[str] | None = None, lease_sec: int = 300
    ) -> Job | None: ...
    async def mark_done(self, job_id: str) -> None: ...
    async def mark_failed(self, job_id: str, error: str, retry: bool = True) -> None: ...
    async def listen(self) -> AsyncIterator[str]: ...
